### ISSUE TITLE
wpa_supplicant config not traslated correctly

### ISSUE THREAD

**Issue by omblivion** [Blaster1920/RPI_headless_tools#1]
wpa_supplicant.conf

`ssid="nometuawifi"
psk="passwwordtuawifi"`

I do not understand what these Italian words means, can you write them in English? (UK EN)

**Comment by Blaster1920** [comment]
I'm sorry but this repo is meant to aid Italian users, as it is only mentioned inside the https://klipper-italia.xyz/ Klipper Italia website.
I'll have to close this issue
